[package]
name = "argon"
authors = ["Dervex"]
description = "Full featured tool for Roblox development"
repository = "https://github.com/argon-rbx/argon"
documentation = "https://argon.wiki/docs"
homepage = "https://argon.wiki"
license = "Apache-2.0"
version = "0.1.0"
edition = "2021"

[lib]
name = "argon"
path = "src/lib.rs"

[dependencies]
clap = { version = "4.4.1", features = ["derive", "cargo"] }
serde = { version = "1.0.189", features = ["derive"] }
tokio = { version = "1.32.0", features = ["full"] }
clap-verbosity-flag = "2.1.0"
panic-message = "0.3.0"
serde_json = "1.0.107"
env_logger = "0.10.0"
directories = "5.0.1"
backtrace = "0.3.69"
toml_edit = "0.20.5"
dialoguer = "0.11.0"
actix-web = "4.4.0"
globenv = "0.2.0"
colored = "2.0.4"
anyhow = "1.0.75"
notify = "6.1.1"
toml = "0.8.3"
open = "5.0.0"
log = "0.4.20"
awc = "3.2.0"
