[package]
name = "argon"
authors = ["Dervex"]
description = "Full featured tool for Roblox development"
repository = "https://github.com/argon-rbx/argon"
documentation = "https://argon.wiki/docs"
homepage = "https://argon.wiki"
license = "Apache-2.0"
version = "0.1.0"
edition = "2021"

[lib]
name = "argon"
path = "src/lib.rs"

[dependencies]
rbx_xml = "0.13.2"
rbx_binary = "0.7.3"
rbx_dom_weak = "2.6.0"
rbx_reflection = "4.4.0"
rbx_reflection_database = "0.2.9"

config-derive = { version = "*", path = "crates/config-derive" }

clap = { version = "4.4.1", features = ["derive", "cargo"] }
serde = { version = "1.0.189", features = ["derive"] }
tokio = { version = "1.32.0", features = ["full"] }

notify-debouncer-full = "0.3.1"
clap-verbosity-flag = "2.1.0"
crossbeam-channel = "0.5.8"
roblox_install = "1.0.0"
panic-message = "0.3.0"
self-replace = "1.3.7"
serde_json = "1.0.107"
env_logger = "0.10.0"
directories = "5.0.1"
backtrace = "0.3.69"
documented = "0.2.0"
dialoguer = "0.11.0"
actix-web = "4.4.0"
multimap = "0.9.1"
optfield = "0.3.0"

json2lua = "0.1.2"
globenv = "0.2.1"
pathsub = "0.1.1"

walkdir = "2.4.0"
colored = "2.0.4"
anyhow = "1.0.75"
chrono = "0.4.31"
notify = "6.1.1"
whoami = "1.4.1"
ctrlc = "3.4.2"
toml = "0.8.3"
glob = "0.3.1"
open = "5.0.0"
log = "0.4.20"
awc = "3.2.0"
csv = "1.3.0"

[patch.crates-io]
notify-debouncer-full = { path = "crates/notify-debouncer-full" }
